import { SourceLine } from '../../../../line-data';

export const line = {
  columns: [
    'barcode',
    'itemId',
    'vpn',
    'itemDescription',
    'color',
    'size',
    'dept',
    'deptName',
    'class',
    'className',
    'subclass',
    'subclassName',
    'itemCost',
  ],
  mandatoryFields: ['barcode', 'itemId', 'vpn', 'itemCost'],
  identifierMappings: { barcode: 'barcode', sku: 'ItemId' },
  outputMappings: {
    active: 'yes',
    sku: 'itemId',
    barcode: 'barcode',
    model_code: '',
    part_number: '',
    internal_ref: '',
    supplier_ref: '',
    supplier_name: '',
    name: '',
    description: '',
    rsp: '',
    cost: '',
    brand: '',
    depart_ref: '',
    depart_name: '',
    class_ref: '',
    class_name: '',
    color: '',
    style: '',
    size: '',
    gender: '',
    season: '',
    is_serialized: '',
    is_batched: '',
    uom: 'g',
    category1: '',
    category1_ref: '',
    category2: '',
    category2_ref: '',
    category3: '',
    category3_ref: '',
    category4: '',
    category4_ref: '',
    category5: '',
    category5_ref: '',
    category6: '',
    category6_ref: '',
    category7: '',
    category7_ref: '',
    extra1: '',
    extra2: '',
    extra3: '',
    extra4: '',
    extra5: '',
  },
  separator: '|',
  withHeader: false,
};

export const output = {
  // filename: 'Item Master.txt',
  filename: function (args: SourceLine) {
    return args.output?.brandName
      ? `${args.output?.brandName} - Item Master - ${Date.now()}.txt`
      : `Item Master - ${Date.now()}.csv`;
  },
  // header: 'sample header\n',
  // footer: 'sample footer',
  // header: (args: SourceLine) => generatorOptions.columns.join(generatorOptions.separator) + '\n',
  // footer: 'sample footer',
  separator: ';',
  // template: 'false;{BARCODE};{PART_NUMBER};{DESCRIPTION};g',
};
