import { LineOutputOptions, LineSourceBaseOptions } from '../../../../index';

export const line: LineSourceBaseOptions = {
  columns: [
    'ProductId',
    'IsExcluded',
    'SKU',
    'Description',
    'Style',
    'MasterStyle',
    'Color',
    'ColorCode',
    'Size',
    'SizeCode',
    'CategoryId',
    'ImageUri',
    'SeasonCode',
    'CastorArticleID',
    'CustomAliases',
  ],
  mandatoryFields: ['SKU', 'ProductId', 'Description', 'CategoryId'],
  identifierMappings: { barcode: 'ProductId', sku: 'SKU' },
  outputMappings: {
    TYPE_MOUVEMENT: 'M',
    CODE_ARTICLE: 'SKU',
    MAIN_EAN: 'ProductId',
    CODE_PRODUCT: '',
    SHORT_LABEL: 'Description',
    LONG_LABEL: '',
    CODE_SEASON: 'SeasonCode',
    CODE_SUPPLIER: '',
    CODE_FAMILY: 'CategoryId',
    CODE_NGP: '',
    CODE_COLOR: 'ColorCode',
    CODE_SIZE: 'SizeCode',
    PRIMARY_TYPE_TAG: '',
    SECONDARY_TYPE_TAG: '',
    SELLING_PRICE: '',
    BUYING_PRICE: '',
    URL_PICTURE: '',
    TRACEABILITY_MODE: '',
    SUPPLIER_REF: '',
    END_PRODUCT: '',
    QUANTITY: '',
    UNIT: '',
    FIDELITY_PRICE: '',
    USERFIELD_1: '',
    USERFIELD_2: '',
    USERFIELD_3: '',
    USERFIELD_4: '',
    USERFIELD_5: '',
    CODE_BRAND: '',
    PRICE_COMPARISON_UNIT: '',
    PRICE_COMPARISON_DIVIDER: '',
    RANK: '',
  },
  separator: ',',
  withHeader: true,
};

export const output: LineOutputOptions = {
  filename: {
    template: 'I_SKU_[timestamp].csv',
  },
  header:
    'TYPE_MOUVEMENT;CODE_ARTICLE;MAIN_EAN;CODE_PRODUCT;SHORT_LABEL;LONG_LABEL;CODE_SEASON;CODE_SUPPLIER;CODE_FAMILY;CODE_NGP;CODE_COLOR;CODE_SIZE;PRIMARY_TYPE_TAG;SECONDARY_TYPE_TAG;SELLING_PRICE;BUYING_PRICE;URL_PICTURE;TRACEABILITY_MODE;SUPPLIER_REF;END_PRODUCT;QUANTITY;UNIT;FIDELITY_PRICE;USERFIELD_1;USERFIELD_2;USERFIELD_3;USERFIELD_4;USERFIELD_5;CODE_BRAND;PRICE_COMPARISON_UNIT;PRICE_COMPARISON_DIVIDER;RANK\n',
  // footer: 'sample footer',
  // header: (args: SourceLine) => generatorOptions.columns.join(generatorOptions.separator) + '\n',
  // footer: 'sample footer',
  separator: ';',
  uniqueKey: 'SKU',
  // template: 'false;{BARCODE};{PART_NUMBER};{DESCRIPTION};g',
};
