service: etl-utility

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  timeout: 900
  memorySize: 1024

functions:
  go-etl:
    handler: bootstrap
    package:
      artifact: bootstrap.zip
    url: true
