import { LineOutputOptions, LineSourceBaseOptions } from 'etl-utility';

export const line: LineSourceBaseOptions = {
  columns: [
    'barcode',
    'itemId',
    'vpn',
    'itemDescription',
    'color',
    'size',
    'dept',
    'deptName',
    'class',
    'className',
    'subclass',
    'subclassName',
    'itemCost',
    'rfid',
  ],
  mandatoryFields: ['barcode', 'itemId'],
  identifierMappings: {
    barcode: 'barcode',
    sku: 'itemId',
  },
  outputMappings: {
    TYPE_MOUVEMENT: 'M',
    CODE_ARTICLE: 'itemId',
    MAIN_EAN: '',
    CODE_PRODUCT: 'barcode',
    SHORT_LABEL: 'itemDescription',
    LONG_LABEL: '',
    CODE_SEASON: '',
    CODE_SUPPLIER: '',
    CODE_FAMILY: 'default_family',
    CODE_NGP: '',
    CODE_COLOR: 'color',
    CODE_SIZE: 'size',
    PRIMARY_TYPE_TAG: `[return (input.rfid == 'Y') ? 'HM1' : '']`,
    SECONDARY_TYPE_TAG: `[return (input.rfid == 'Y') ? 'HM2' : '']`,
    SELLING_PRICE: 'itemCost',
    BUYING_PRICE: 'itemCost',
    URL_PICTURE: '',
    TRACEABILITY_MODE: '',
    SUPPLIER_REF: 'vpn',
    END_PRODUCT: '',
    QUANTITY: '',
    UNIT: '',
    FIDELITY_PRICE: '',
    USERFIELD_1: 'barcode',
    USERFIELD_2: '',
    USERFIELD_3: '',
    USERFIELD_4: '',
    USERFIELD_5: '',
    CODE_BRAND: '',
    PRICE_COMPARISON_UNIT: '',
    PRICE_COMPARISON_DIVIDER: '',
    RANK: '',
  },
  separator: '|',
  withHeader: false,
};

export const output: LineOutputOptions = {
  filename: {
    template: 'I_SKU_[timestamp].csv',
  },
  header:
    'TYPE_MOUVEMENT;CODE_ARTICLE;MAIN_EAN;CODE_PRODUCT;SHORT_LABEL;LONG_LABEL;CODE_SEASON;CODE_SUPPLIER;CODE_FAMILY;CODE_NGP;CODE_COLOR;CODE_SIZE;PRIMARY_TYPE_TAG;SECONDARY_TYPE_TAG;SELLING_PRICE;BUYING_PRICE;URL_PICTURE;TRACEABILITY_MODE;SUPPLIER_REF;END_PRODUCT;QUANTITY;UNIT;FIDELITY_PRICE;USERFIELD_1;USERFIELD_2;USERFIELD_3;USERFIELD_4;USERFIELD_5;CODE_BRAND;PRICE_COMPARISON_UNIT;PRICE_COMPARISON_DIVIDER;RANK',
  separator: ';',
  uniqueKey: 'itemId',
};
