import { LineOutputOptions, LineSourceBaseOptions } from '../../../../index';

export const line: LineSourceBaseOptions = {
  columns: [
    'type',
    'subType',
    'documentNumber',
    'globalExternalReference',
    'parentExternalReference',
    'userReason',
    'supplierCode',
    'trackingNumber',
    'toSiteCode',
    'removalLocation',
    'parcelCount',
    'receiptDate',
    'totalExpectedQuantity',
    'totalControlRemainingQuantity',
    'totalControlQuantityProcessed',
    'totalControlQuantityCancelled',
    'globalControlStatus',
    'globalControlDate',
    'isOversupply',
    'globalStatus',
    'linePosition',
    'externalReference',
    'skuCode',
    'expectedQuantity',
    'controlRemainingQuantity',
    'controlQuantityProcessed',
    'controlQuantityCancelled',
    'parcelNumber',
    'palletNumber',
    'controlStatus',
    'controlDate',
    'status',
    'epc',
  ],
  mandatoryFields: [],
  identifierMappings: {},
  outputMappings: {
    'root.TaskID': 'globalExternalReference',
    'root.Status': 'AUTHRISED',
    'Lines[].Date': 'receiptDate',
    'Lines[].Quantity': 'controlQuantityProcessed',
    'Lines[].SKU': 'skuCode',
    'Lines[].Location': 'toSiteCode',
    'Lines[].Received': 'TRUE',
  },
  separator: ';',
  withHeader: true,
};

export const output: LineOutputOptions = {
  filename: {
    template: '{parentExternalReference}-cin7-po-receving.json',
  },
  template:
    '{"Date": "{receiptDate}", "Quantity": "{controlQuantityProcessed}", "SKU": "{skuCode}", "Location": "{toSiteCode}", "Received": false}',
  header: '{"TaskID": "{globalExternalReference}", "Status": "AUTHORISED"}',
  arrayField: 'Lines',
  separator: ';',
};
