const config = {
  line: {
    columns: [
      'type',
      'subType',
      'documentNumber',
      'globalExternalReference',
      'parentExternalReference',
      'userReason',
      'supplierCode',
      'trackingNumber',
      'toSiteCode',
      'removalLocation',
      'parcelCount',
      'receiptDate',
      'totalExpectedQuantity',
      'totalControlRemainingQuantity',
      'totalControlQuantityProcessed',
      'totalControlQuantityCancelled',
      'globalControlStatus',
      'globalControlDate',
      'isOversupply',
      'globalStatus',
      'linePosition',
      'externalReference',
      'skuCode',
      'expectedQuantity',
      'controlRemainingQuantity',
      'controlQuantityProcessed',
      'controlQuantityCancelled',
      'parcelNumber',
      'palletNumber',
      'controlStatus',
      'controlDate',
      'status',
    ],
    mandatoryFields: [],
    identifierMappings: {},
    outputMappings: {
      'root.TaskID': 'globalExternalReference',
      'root.Status': 'AUTHRISED',
      'Lines[].Date': 'receiptDate',
      'Lines[].Quantity': 'controlQuantityProcessed',
      'Lines[].SKU': 'skuCode',
      'Lines[].Location': 'toSiteCode',
      'Lines[].Received': 'TRUE',
    },
    separator: ';',
    withHeader: true,
  },
  output: {
    filename: {
      template: '{parentExternalReference}-cin7-po-receving.json',
    },
    template:
      '{"Date": "{receiptDate}", "Quantity": "{controlQuantityProcessed}", "SKU": "{skuCode}", "LocationID": "{toSiteCode}", "Received": true}',
    header: '{"TaskID": "{globalExternalReference}", "Status": "AUTHORISED"}',
    separator: ';',
    arrayField: 'Lines',
    dataset_type: 'json',
    fileGenerator: 'json-generator',
  },
};

export default config;
